# Generated by Django 2.1.5 on 2019-02-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('RollNo', models.CharField(max_length=10, unique=True)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Url', models.URLField(blank=True)),
                ('DOB', models.DateField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
    ]
